name: Deploy WordPress theme

on:
  push:
    branches: ["main"]

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 Bundling WordPress theme"

      - name: Checkout repository code
        uses: actions/checkout@v3

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install
      - run: npm run bundle

      - name: Deploy theme in production
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: bundle
          remote_path: ${{secrets.TARGET}}
          remote_host: ${{secrets.HOST}}
          remote_user: ${{secrets.USER}}
          remote_key: ${{secrets.DEPLOY_KEY}}
